In [2]:
%run ../dashboard/data_loader.py

2026-05-11 13:52:02.042 No runtime found, using MemoryCacheStorageManager
2026-05-11 13:52:02.043 No runtime found, using MemoryCacheStorageManager
2026-05-11 13:52:02.043 No runtime found, using MemoryCacheStorageManager
2026-05-11 13:52:02.044 No runtime found, using MemoryCacheStorageManager
2026-05-11 13:52:02.044 No runtime found, using MemoryCacheStorageManager
2026-05-11 13:52:02.044 No runtime found, using MemoryCacheStorageManager

In [8]:
# Load all data from sales table.
# Should not be done in production environment!
# Should aggregate with SQL first.
df = fetch_all_sales_rows()
df

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method
0,1,1,INV-202301-00001,2023-01-10,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart
1,2,2,INV-202301-00002,2023-01-16,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks
2,3,3,INV-202301-00003,2023-01-05,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks
3,4,4,INV-202301-00004,2023-01-02,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha
4,5,5,INV-202301-00005,2023-01-13,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart
...,...,...,...,...,...,...,...,...,...,...,...,...
10113,10114,10114,INV-202502-00344,2025-02-26,3878.0,1275,1,62.82,62.82,pood,Tallinn,kaart
10114,10115,10115,INV-202502-00345,2025-02-11,3991.0,1114,1,74.70,-74.70,pood,Tartu,järelmaks
10115,10116,10116,INV-202502-00346,2025-02-18,2133.0,1003,1,52.04,52.04,online,None,järelmaks
10116,10117,10117,INV-202502-00347,2025-02-22,2908.0,1278,1,263.13,263.13,online,None,järelmaks
10117,10118,10118,INV-202502-00348,2025-02-27,NaN,1191,1,230.06,230.06,pood,Tallinn,sularaha

In [9]:
# 5 first rows from sales table.
df.head()

,id,sale_id,invoice_id,sale_date,customer_id,product_id,quantity,unit_price,total_price,channel,store_location,payment_method
0,1,1,INV-202301-00001,2023-01-10,2588.0,1274,2,234.79,469.58,pood,Tallinn,kaart
1,2,2,INV-202301-00002,2023-01-16,4338.0,1207,2,241.13,482.26,pood,Pärnu,järelmaks
2,3,3,INV-202301-00003,2023-01-05,4673.0,1264,1,258.46,221.19,pood,Pärnu,järelmaks
3,4,4,INV-202301-00004,2023-01-02,4677.0,1341,3,45.21,135.63,pood,Tartu,sularaha
4,5,5,INV-202301-00005,2023-01-13,2390.0,1284,1,99.57,99.57,pood,Tartu,kaart

In [10]:
# number of rows x number of columns
df.shape

(10118, 12)

In [11]:
# Number of rows in sales table.
df.shape[0]

10118